# POPESCU Matei 315CB #
build:
	gcc main.c -std=gnu11 -o tema1 functiiBanda.c functiiComenzi.c functiiUndoRedo.c

run:
	./tema1

clean:
	rm tema1

valgrind:
	valgrind --leak-check=yes --track-origins=yes ./tema1